<div class="inner-content">
    <div class="panel theme-panel">
        <div class="panel-heading">

            <span class="panel-title">
                Carrera<i class="fa fa-pencil-square-o"></i>
            </span>
        </div>
        <div class="alert alert-success" role="alert" id="success" style="display: none;" align="center">Empresa activada</div>
        <div id="table">

            <div class="panel-body table-responsive" >
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>No. Carrera</th>
                            <th>Carrera</th>
                            <th>Semestres</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $a = 0;
                        foreach ($this->paginator as $carrera) : // <-- change here!  
                            $a++;
                            ?>
                            <tr>
                                <td><?php echo $this->escapeHtml($carrera->id_carrera); ?></td>
                                <td><?php echo $this->escapeHtml($carrera->carrera); ?></td>
                                <td><?php echo $this->escapeHtml($carrera->semestres_totales); ?></td>
                                <td><?php
                                    if ($carrera->status == 1)
                                        echo "Activa";
                                    else
                                        echo 'Desactivada';
                                    ?></td>


                                <td><a href="#" id="ver<?php echo $a; ?>" carrera="<?php echo $carrera->id_carrera; ?>"
                                       status="<?php echo $carrera->status; ?>"
                                       onclick="anclaF(this)">Ver</a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?php
                if ($this->paginator->count() == 0)
                    echo"<h1 align='center'>No hay empresas por validar</h1>";
                ?>
            </div>
            <div class="modal fade" id="myModal" role="dialog">
                <div class="modal-dialog modal-sm">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title" align="center">Carrera</h4>
                        </div>
                        <div class="modal-body" id="bodymodal">
                            <input type="number" name="digito" class="form-control" > 
                        </div>
                        <div class="modal-footer"><div align="left" id="footer" >
                                
                            </div>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                        </div>

                    </div>
                </div>
            </div>
            <?php
            // add at the end of the file after the table
            echo $this->paginationControl(
                    // the paginator object
                    $this->paginator,
                    // the scrolling style
                    'sliding',
                    // the partial to use to render the control
                    'partial/paginator.phtml',
                    // the route to link to when a user clicks a control link
                    array(
                'url' => $this->url('Administrador', array('controller' => 'Administrador', 'action' => 'carrera'))
                    )
            );
            ?>
        </div>
    </div>
</div>
<script>
    function anclaF(e) {
        $("#myModal").modal("show");
        $('#bodymodal').html('<div align="center"><img src="http://img.ffffound.com/static-data/assets/6/77443320c6509d6b500e288695ee953502ecbd6d_m.gif"/></div>');
        if ($(e).attr("status") === "1") {
            $("#footer").html('<button type="button" class="btn btn-default" onclick="autorizarF(this)" disabled data-dismiss="modal">Autorizar</button><button type="button" class="btn btn-default" onclick="rechazarF(this)" data-dismiss="modal">Rechazar</button>');
        } 
        else if ($(e).attr("status") === "0") {
            $("#footer").html('<button type="button" class="btn btn-default" onclick="autorizarF(this)"  data-dismiss="modal">Autorizar</button>'
                    + '<button type="button" class="btn btn-default" onclick="rechazarF(this)" disabled data-dismiss="modal">Rechazar</button>');
        }
    }
    function autorizarF(e) {
        $.post('empresaactivas', {id_rfc: $(e).attr("rfc"), digito_verificador: $(e).attr("digito"), autorizacion: 1})
                .done(function () {
                    var success = document.getElementById("success");
                    success.style.display = "block";
                    setTimeout(function () {
                        $('#success').html('Empresa Autorizada');
                        document.getElementById("success").style.display = "none";
                        $("#table").load("empresapendiente #table");
                    }, 2000);
                })
                .fail(function (data) {
                    alert(data);
                });
    }
    function rechazarF(e) {
        $.post('empresaactivas', {id_rfc: $(e).attr("rfc"), digito_verificador: $(e).attr("digito"), autorizacion: 2})
                .done(function () {
                    var success = document.getElementById("success");
                    success.style.display = "block";
                    setTimeout(function () {
                        $('#success').html('Empresa Rechazada');
                        document.getElementById("success").style.display = "none";
                        $("#table").load("empresapendiente #table");
                    }, 2000);
                })
                .fail(function (data) {
                    alert(data);
                });
    }
</script>