<div class="inner-content">
    <div class="panel theme-panel">
        <div class="panel-heading">

            <span class="panel-title">
                Empresa Activas <i class="fa fa-pencil-square-o"></i>
            </span>
        </div>
        <div class="alert alert-success" role="alert" id="success" style="display: none;" align="center">Empresa desactivada</div>
        <div id="table">

            <div class="panel-body table-responsive" >
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Empresa</th>
                            <th>RFC</th>
                            <th>Razon social</th>
                            <th>Telefono</th>
                            <th>Correo</th>
                            <th>Giro</th>
                            <th>Ver</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $a = 0;
                        foreach ($this->paginator as $empresa) : // <-- change here!  
                            $a++;
                            ?>
                            <tr>
                                <td><?php echo $this->escapeHtml($empresa->nombre_comercial); ?></td>
                                <td><?php echo $this->escapeHtml($empresa->id_rfc); ?></td>
                                <td><?php echo $this->escapeHtml($empresa->razon_social); ?></td>
                                <td><?php echo $this->escapeHtml($empresa->telefono); ?></td>
                                <td><?php echo $this->escapeHtml($empresa->correo_electronico); ?></td>
                                <td><?php echo $this->escapeHtml($empresa->giro_empresa); ?></td>
                                <td><a href="#" id="ver<?php echo $a; ?>" rfc="<?php echo $empresa->id_rfc; ?>"
                                       digito="<?php echo $empresa->digito_verificador; ?>"
                                       onclick="anclaF(this)">Ver</a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?php
                if ($this->paginator->count() == 0)
                    echo"<h1 align='center'>No hay empresas por mostrar</h1>";
                ?>
            </div>
            <div class="modal fade" id="myModal" role="dialog">
                <div class="modal-dialog modal-sm">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title" align="center">Empresa</h4>
                        </div>
                        <div class="modal-body" id="bodymodal">
                            <input type="number" name="digito" class="form-control" > 
                        </div>


                    </div>
                </div>
            </div>
            <?php
            // add at the end of the file after the table
            echo $this->paginationControl(
                    // the paginator object
                    $this->paginator,
                    // the scrolling style
                    'sliding',
                    // the partial to use to render the control
                    'partial/paginator.phtml',
                    // the route to link to when a user clicks a control link
                    array(
                'url' => $this->url('Administrador', array('controller' => 'Administrador', 'action' => 'empresaactivas'))
                    )
            );
            ?>
        </div>
    </div>
</div>
<script>
    function anclaF(e) {
        $("#myModal").modal("show");
        $('#bodymodal').html('<div align="center"><img src="http://img.ffffound.com/static-data/assets/6/77443320c6509d6b500e288695ee953502ecbd6d_m.gif"/></div>');
        $("#bodymodal").load("empresaid", {id_rfc: $(e).attr("rfc"),
            digito_verificador: $(e).attr("digito")
        });
    }
    function autorizarF(e) {
        $.post('empresaactivas', {id_rfc: $(e).attr("rfc"), digito_verificador: $(e).attr("digito"), autorizacion: 1})
                .done(function () {
                    var success = document.getElementById("success");
                    success.style.display = "block";
                    setTimeout(function () {
                        document.getElementById("success").style.display = "none";
                        $("#table").load("empresaactivas #table");
                    }, 2000);
                })
                .fail(function (data) {
                    alert(data);
                });
    }
    function rechazarF(e) {
        $.post('empresaactivas', {id_rfc: $(e).attr("rfc"), digito_verificador: $(e).attr("digito"), autorizacion: 2})
                .done(function () {
                    var success = document.getElementById("success");
                    success.style.display = "block";
                    setTimeout(function () {
                        document.getElementById("success").style.display = "none";
                        $("#table").load("empresaactivas #table");
                    }, 2000);
                })
                .fail(function (data) {
                    alert(data);
                });
    }
</script>