<div class="inner-content">
    <div class="panel theme-panel">
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-pencil-square-o fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">.</div>
                            <div>Vacantes para revisar</div>
                        </div>
                    </div>
                </div>
                <a href="#" id="vpendientes">
                    <div class="panel-footer">
                        <span class="pull-left">Ver Detalles</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel " style="background-color: #5cb85c;">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-table fa-5x" style="color: white;"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge"></div>
                            <div style="color: white;">Reportes</div>
                        </div>
                    </div>
                </div>
                <a href="#" id="reportes2">
                    <div class="panel-footer">
                        <span class="pull-left">Ver Detalles</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel " style="background-color: #f0ad4e;">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-copyright fa-5x" style="color: white;"></i>
                        </div>
                        <div class="col-xs-9 text-right"style="color: white;">
                            <div class="huge">Empresas</div>
                            <div>Pendientes</div>
                        </div>
                    </div>
                </div>
                <a href="#" id="ependientes">
                    <div class="panel-footer">
                        <span class="pull-left">Ver Detalles</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel "style="background-color: #d9534f;" style="color: white;">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-picture-o fa-5x" style="color: white;"></i>
                        </div>
                        <div class="col-xs-9 text-right" style="color: white">
                            <div class="huge"></div>
                            <div>Imagenes de banner</div>
                        </div>
                    </div>
                </div>
                <a href="#" id="imagenes2">
                    <div class="panel-footer">
                        <span class="pull-left">Ver Detalles</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right" ></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-clock-o fa-fw"></i> Actividad reciente
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <ul class="timeline">
                    <?php $n=0;foreach ($ingresos as $datos) {?>
                    <li class="<?php if($n%2!=0) echo "timeline-inverted";?>">
                        <div class="timeline-badge warning"><i class="<?php if ($datos["titulo"]=="interesados") echo "fa fa-check"; else echo "fa fa-key"; ?>"></i>
                        </div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4 class="timeline-title"><?php echo $datos["titulo"];?></h4>
                                <p><small class="text-muted"><i class="fa fa-clock-o"></i><?php echo $datos["fecha"];?></small>
                                </p>
                            </div>
                            <div class="timeline-body">
                                <p><?php if ($datos["titulo"]=="interesados") echo 'El alumno '.$datos["Alumno"].' acaba de postularse a una vacante de '.$datos["puesto"].' de la empresa '.$datos["empresa"];
                                if($datos["contratado"]==1) echo " y fue contaratado "; if($datos["titulo"]=="ingresos")echo 'El alumno '.$datos["Alumno"].' acaba de ingresar al sistema';
                                ?></p>
                            </div>
                        </div>
                    </li>
                    <?php $n++; } ?>
                    
                </ul>
            </div>
            <!-- /.panel-body -->
        </div>
    </div>
</div>
<script>
    $("#ependientes").on('click', function (event) {
        history.pushState(null, 'Empresa  Pendiente', 'empresapendiente');
        cargar();
        $("#main-content").load("empresapendiente");
    });
    $("#vpendientes").on('click', function (event) {
        history.pushState(null, 'Empresa  Pendiente', 'vacantependiente');
        cargar();
        $("#main-content").load("vacantependiente");
    });
    $("#imagenes2").on('click', function (event) {
        history.pushState(null, 'Empresa  Pendiente', 'imagenes');
        cargar();
        $("#main-content").load("imagenes");
    });
    $("#reportes2").on('click', function (event) {
        history.pushState(null, 'reportes', 'reportes');
        cargar();
        $("#main-content").load("reportes");
    });
    function cargar()
    {
        $('#main-content').html('<div align="center"><img src="http://img.ffffound.com/static-data/assets/6/77443320c6509d6b500e288695ee953502ecbd6d_m.gif"/></div>');
    }
</script>
