<div class="inner-content">
    <div class="panel theme-panel">
        <div class="panel-heading">

            <span class="panel-title">
                Vacantes <i class="fa fa-pencil-square-o"></i>
            </span>
        </div>
        <div class="alert alert-success" role="alert" id="success" style="display: none;" align="center">Te has postulado correctamente</div>
        <div id="table">

            <div class="panel-body table-responsive" >
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Empresa</th>
                            <th>Puesto</th>
                            <th>Sexo</th>
                            <th>Motivos</th>
                            <th>Detalles</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $a = 0;
                        foreach ($this->paginator as $empresa) : // <-- change here!  
                            $a++;
                            ?>
                            <tr>
                                <td><?php echo $this->escapeHtml($empresa->nombre_comercial); ?></td>
                                <td><?php echo $this->escapeHtml($empresa->puesto); ?></td>
                                <td><?php echo $this->escapeHtml($empresa->sexo); ?></td>
                                <td><?php echo $this->escapeHtml($empresa->motivos); ?></td>
                                <td><a href="#" id="ver<?php echo $a; ?>" rfc="<?php echo $empresa->id_rfc; ?>"
                                       digito="<?php echo $empresa->digito_verificador; ?>" 
                                       vacante="<?php echo $empresa->num_vacante; ?> 
                                       " onclick="verF(this)">Ver</a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <div class="modal fade" id="myModal" role="dialog">
                <div class="modal-dialog modal-sm">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title" align="center">Vacante rechazada</h4>
                        </div>
                        <div class="modal-body" id="bodymodal">
                            <input type="number" name="digito" class="form-control" > 
                        </div>


                    </div>
                </div>
            </div>
            <?php
            // add at the end of the file after the table
            echo $this->paginationControl(
                    // the paginator object
                    $this->paginator,
                    // the scrolling style
                    'sliding',
                    // the partial to use to render the control
                    'partial/paginator.phtml',
                    // the route to link to when a user clicks a control link
                    array(
                'url' => $this->url('Administrador', array('controller' => 'Administrador', 'action' => 'vacanterechazada'))
                    )
            );
            ?>
        </div>
    </div>
</div>
<script>
    function verF(e) {
        $("#myModal").modal("show");
        $('#bodymodal').html('<div align="center"><img src="http://img.ffffound.com/static-data/assets/6/77443320c6509d6b500e288695ee953502ecbd6d_m.gif"/></div>');
        $("#bodymodal").load("vacanteid", {id_rfc: $(e).attr("rfc"),
            digito_verificador: $(e).attr("digito"), num_vacante: $(e).attr("vacante")
        });
    }
    function postularF(e) {
        $.post('vacantes', {id_rfc: $(e).attr("rfc"), num_vacante: $(e).attr("vacante"),
            digito_verificador: $(e).attr("digito")})
                .done(function () {
                    var success = document.getElementById("success");
                    success.style.display = "block";
                    setTimeout(function () {
                        document.getElementById("success").style.display = "none";
                    }, 2000);
                })
                .fail(function (data) {
                    alert(data);
                });
    }
    function autorizarF(e) {
        $.post('vacanteactiva', {id_rfc: $(e).attr("rfc"), digito_verificador: $(e).attr("digito"), 
            num_vacante:$(e).attr("num_vacante"),status: 1})
                .done(function () {
                    var success = document.getElementById("success");
                    success.style.display = "block";
                    setTimeout(function () {
                        document.getElementById("success").style.display = "none";
                        $("#table").load("vacanteactiva #table");
                    }, 2000);
                })
                .fail(function (data) {
                    alert(data);
                });
    }
    function rechazarF(e) {
        $.post('vacanteactiva', {id_rfc: $(e).attr("rfc"), digito_verificador: $(e).attr("digito"), 
            num_vacante:$(e).attr("num_vacante"),status: 2})
                .done(function () {
                    var success = document.getElementById("success");
                    success.style.display = "block";
                    setTimeout(function () {
                        document.getElementById("success").style.display = "none";
                        $("#table").load("vacanteactiva #table");
                    }, 2000);
                })
                .fail(function (data) {
                    alert(data);
                });
    }
</script>