<div class="modal fade" id="vacanteRechazada" role="dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title" align="center">Motivos del rechazo</h4>
            </div>
            <form id="motivosRechazo" method="post" action="empresa" role="form">
                <div class="modal-body">
                    <input type="text" name="motivos" class="form-control" > 
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-default" onclick="rechazaF(this)">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="inner-content">
    <div class="panel theme-panel">
        <div class="panel-heading">

            <span class="panel-title">
                Vacantes <i class="fa fa-pencil-square-o"></i>
            </span>
        </div>
        <div class="alert alert-success" role="alert" id="success" style="display: none;" align="center">Se han hecho los cambios</div>
        <div id="table">

            <div class="panel-body table-responsive" >
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Empresa</th>
                            <th>Puesto</th>
                            <th>Sueldo</th>
                            <th>Sexo</th>
                            <th>Edad</th>
                            <th>Horario</th>
                            <th>Dias a laborar</th>
                            <th>Detalles</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $a = 0;
                        foreach ($this->paginator as $empresa) : // <-- change here!  
                            $a++;
                            ?>
                            <tr>
                                <td><?php echo $this->escapeHtml($empresa->nombre_comercial); ?></td>
                                <td><?php echo $this->escapeHtml($empresa->puesto); ?></td>
                                <td><?php echo $this->escapeHtml($empresa->sueldo); ?></td>
                                <td><?php echo $this->escapeHtml($empresa->sexo); ?></td>
                                <td><?php echo $this->escapeHtml($empresa->edad); ?></td>
                                <td><?php echo $this->escapeHtml($empresa->horario_a_laborar); ?></td>
                                <td><?php echo $this->escapeHtml($empresa->dias_a_laborar); ?></td>
                                <td><a href="#" id="ver<?php echo $a; ?>" rfc="<?php echo $empresa->id_rfc; ?>"
                                       digito="<?php echo $empresa->digito_verificador; ?>" 
                                       vacante="<?php echo $empresa->num_vacante; ?> 
                                       " onclick="verF(this)">Ver</a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <div class="modal fade" id="myModal" role="dialog">
                <div class="modal-dialog modal-sm">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title" align="center">Vacante Pendiente</h4>
                        </div>
                        <div class="modal-body" id="bodymodal">
                            <input type="number" name="digito" class="form-control" > 
                        </div>


                    </div>
                </div>
            </div>
            <?php
            // add at the end of the file after the table
            echo $this->paginationControl(
                    // the paginator object
                    $this->paginator,
                    // the scrolling style
                    'sliding',
                    // the partial to use to render the control
                    'partial/paginator.phtml',
                    // the route to link to when a user clicks a control link
                    array(
                'url' => $this->url('Administrador', array('controller' => 'Administrador', 'action' => 'vacantependiente'))
                    )
            );
            ?>
        </div>
    </div>
</div>
<script>
    function verF(e) {
        $("#myModal").modal("show");
        $('#bodymodal').html('<div align="center"><img src="http://img.ffffound.com/static-data/assets/6/77443320c6509d6b500e288695ee953502ecbd6d_m.gif"/></div>');
        $("#bodymodal").load("vacanteid", {id_rfc: $(e).attr("rfc"),
            digito_verificador: $(e).attr("digito"), num_vacante: $(e).attr("vacante")
        });
    }
    function postularF(e) {
        $.post('vacantes', {id_rfc: $(e).attr("rfc"), num_vacante: $(e).attr("vacante"),
            digito_verificador: $(e).attr("digito")})
                .done(function () {
                    var success = document.getElementById("success");
                    success.style.display = "block";
                    setTimeout(function () {
                        document.getElementById("success").style.display = "none";
                    }, 2000);
                })
                .fail(function (data) {
                    alert(data);
                });
    }
    function autorizarF(e) {
        $.post('vacanteactiva', {id_rfc: $(e).attr("rfc"), digito_verificador: $(e).attr("digito"),
            num_vacante: $(e).attr("num_vacante"), status: 1})
                .done(function () {
                    var success = document.getElementById("success");
                    success.style.display = "block";
                    setTimeout(function () {
                        document.getElementById("success").style.display = "none";
                        $("#table").load("vacantependiente #table");
                    }, 2000);
                })
                .fail(function (data) {
                    alert(data);
                });
    }
    var rfc = "", digito, num_vacante;

    $(document).ready(function () {
        $("#motivosRechazo").submit(function (e) {
            e.preventDefault();
            var motivos = ($("#motivosRechazo").serialize()).substring(8);
            if (motivos.length === 0) {
                alert("Tiene que dar motivos");
                exit();
            }
            $.post('vacanteactiva', {id_rfc: rfc, digito_verificador: digito,
                num_vacante: num_vacante, motivos: motivos, status: 2})
                    .done(function () {
                        $("#vacanteRechazada").modal("hide");
                        $("#table").load("vacantependiente #table");
                        var success = document.getElementById("success");
                        success.style.display = "block";
                        setTimeout(function () {
                            document.getElementById("success").style.display = "none";

                        }, 2000);
                    })
                    .fail(function (data) {
                        alert(data);
                    });
            e.preventDefault();
        });
    });
    function rechazarF(e) {
        rfc = $(e).attr("rfc");
        digito = $(e).attr("digito");
        num_vacante = $(e).attr("num_vacante");
        $("#vacanteRechazada").modal("show");
    }
</script>