<div class="inner-content">
    <div class="panel theme-panel" >
        <dl class="dl-horizontal">
            <dt>Nombre:</dt>
            <dd><?php echo $vacante["nombre_comercial"]; ?></dd>
            <dt>Giro:</dt>
            <dd><?php echo $vacante["giro_empresa"]; ?></dd>
            <dt>Telefono:</dt>
            <dd><?php echo $vacante["telefono"]; ?></dd>
            <dt>Extensión</dt>
            <dd><?php echo $vacante["extension"]; ?></dd>
            <dt>Email:</dt>
            <dd><?php echo $vacante["correo_electronico"]; ?></dd>
            <dt>Horario de Atencion</dt>
            <dd><?php echo $vacante["horario_atencion"]; ?></dd>
            <dt>Puesto:</dt>
            <dd><?php echo $vacante["puesto"]; ?></dd>
            <dt>Vacantes Disponibles:</dt>
            <dd><?php echo $vacante["vacantes_disponibles"]; ?></dd>
            <dt>Sueldo:</dt>
            <dd><?php echo $vacante["sueldo"]; ?></dd>
            <dt>Edad:</dt>
            <dd><?php echo $vacante["edad"]; ?></dd>
            <dt>Sexo:</dt>
            <dd><?php echo $vacante["sexo"]; ?></dd>
            <dt>Horario a Laborar:</dt>
            <dd><?php echo $vacante["horario_a_laborar"]; ?></dd>
            <dt>Dias a Laborar: </dt>
            <dd><?php echo $vacante["dias_a_laborar"]; ?></dd>
            <dt>Contacto:</dt>
            <dd><?php echo $vacante["contacto"]; ?></dd>
            <dt>Requisitos:</dt>
            <dd><?php echo $vacante["requisitos"]; ?></dd>
            <dt>Experiencia</dt>
            <dd><?php echo $vacante["experiencia"]; ?></dd>
            <dt>Actividades a realizar:</dt>
            <dd><?php echo $vacante["actividades_realizar"]; ?></dd>
            <dt>Autorizacion:</dt>
            <dd><?php
                if ($vacante["status"] == 0)
                    echo "pendiente";
                else if ($vacante["status"] == 1)
                    echo "Autorizada";
                else
                    echo "rechazada";
                ?></dd>
        </dl>
    </div>
</div>
<div class="modal-footer"><div align="left" >
        <button type="button" class="btn btn-default" onclick="autorizarF(this)"<?php
        if ($vacante["status"] == 1)
            echo "disabled";
        ?>  num_vacante="<?php echo $vacante["num_vacante"]; ?>"
                rfc="<?php echo $vacante["id_rfc"]; ?>" digito="<?php echo $vacante["digito_verificador"]; ?>"
                data-dismiss="modal">Autorizar</button>
        <button type="button" class="btn btn-default" onclick="rechazarF(this)"
                rfc="<?php echo $vacante["id_rfc"]; ?>" digito="<?php echo $vacante["digito_verificador"]; ?>"<?php
                if ($vacante["status"] == 2)
                    echo "disabled";
                ?> num_vacante="<?php echo $vacante["num_vacante"]; ?>"
                data-dismiss="modal">Rechazar</button>
    </div>
    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
</div>
