<script src='https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit' async defer></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script> 
<div class="inner-content">
    <div class="panel theme-panel" align="center">
        <div class="alert alert-success" role="alert" id="success" style="display: none;">Contraseña cambiada</div>
        <div class="alert alert-info" role="alert" id="catcha_error" style="display: none;">Prueba que no eres un robot</div>
        <div class="alert alert-warning" role="alert" id="p_igual" style="display: none;">La Contraseña anterior y nueva son la misma</div>
        <?php
// module/Album/view/album/album/add.phtml:
        $title = 'Contraseña';
        $this->headTitle($title);
        ?>
        <h1 align="center"><?php echo $this->escapeHtml($title); ?></h1>
        <?php echo $form->getFormulario(); ?>
        <div class="alert alert-info" role="alert" id="catcha_error" style="display: none;">Prueba que no eres un robot</div>
    </div>
</div>
<script type="text/javascript">
    function comprobar(f) {
        pass_actual = f.pass_actual.value;
        var response = grecaptcha.getResponse();
        var a = document.getElementById("actual");
        var av = document.getElementById("actual_ver");
        var n = document.getElementById("new");
        var r = document.getElementById("new_re");
        var i = document.getElementById("p_igual");
        var c = document.getElementById("catcha_error");
        var retu = true;
        c.style.display = "none";
        a.style.display = "none";
        av.style.display = "none";
        n.style.display = "none";
        r.style.display = "none";
        i.style.display = "none";
        clave1 = f.pass.value;
        clave2 = f.passc.value;
        if (clave1.length < 6) {
            n.style.display = "block";
            retu = false;
        }
        else if (clave1 !== clave2) {
            r.style.display = "block";
            retu = false;
        }
        if (pass_actual === clave1) {
            i.style.display = "block";
            retu = false;
        }
        if (pass_actual.length < 6) {
            a.style.display = 'block';
            retu = false;
        }
        if (pass_actual !== '<?php echo $pass_actual; ?>') {
            av.style.display = 'block';
            retu = false;
        }
        if (response.length === 0) {
            c.style.display = "block";
            retu = false;
        }
        if (retu === false) {
            return retu;
        } else
            return true;

    }

    var onloadCallback = function () {
        grecaptcha.render('recatcha', {
            'sitekey': '6LfOTBoTAAAAALtlWT4UnTrs1BCnR-kCQZSjGLPg',
            'callback': 'correctCaptcha'
        });
    };
    var correctCaptcha = function (response) {
        alert("response");
    };
    $(document).ready(function () {
        $("#passform").submit(function (e) {
            if (comprobar(document.getElementById("passform")) === true)
                $.ajax({
                    type: "POST",
                    url: "password",
                    data: $("#passform").serialize(), // serializes the form's elements.
                    success: function ()
                    {
                        var success = document.getElementById("success");
                        success.style.display = "block";
                        $("#passform").prop('disabled', true);
                    }
                });

            e.preventDefault(); // avoid to execute the actual submit of the form.
        });
    });
</script>