<!--<link href="<?php // echo $this->basePath('css/popup.css');       ?>"media="screen" rel="stylesheet" type="text/css">-->
<style>
    .modalDialog {
        position: fixed;
        font-family: Arial, Helvetica, sans-serif;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        background: rgba(0,0,0,0.8);
        z-index: 99999;
        opacity:0;
        -webkit-transition: opacity 400ms ease-in;
        -moz-transition: opacity 400ms ease-in;
        transition: opacity 400ms ease-in;
        pointer-events: none;
    }

    .modalDialog:target {
        opacity:1;
        pointer-events: auto;
    }
    @media (max-width: 767px) {
        .modalDialog > div {
            width: 300px;
        }
    }
    @media (max-height: 500px) {
        .modalDialog > div {
            height: 80%;
        }
        .modalDialog1 {
            height: 80%;
        }
    }
    @media (min-width: 768px) {
        .modalDialog > div {
            width: 700px;}

    }
    .modalDialog1{
        overflow: auto;
    }
    .modalDialog > div {
        /*width: 400px;*/
        /*overflow: auto;*/
        /*background-color:#3ea2e5;*/
        position: relative;
        margin: 7% auto;
        /*padding: 5px 20px 13px 20px;*/
        border-radius: 10px;
        /*background: #3ea2e5;*/
        /*background: -moz-linear-gradient(#3ea2e5, #999);*/
        background: -webkit-linear-gradient(#3ea2e5, #8BC5F8);
        background-color: #8BC5F8;
        /*background: -o-linear-gradient(#3ea2e5, #999);*/
    }

    .close {
        background: #606061;
        color: #FFFFFF;
        line-height: 25px;
        position: absolute;
        right: -12px;
        text-align: center;
        top: -10px;
        width: 24px;
        text-decoration: none;
        font-weight: bold;
        -webkit-border-radius: 12px;
        -moz-border-radius: 12px;
        border-radius: 12px;
        -moz-box-shadow: 1px 1px 3px #000;
        -webkit-box-shadow: 1px 1px 3px #000;
        box-shadow: 1px 1px 3px #000;
    }

    .close:hover { background: #00d9ff; }
</style>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<script src="http://zend/public/js/jquery.min.js" type="text/javascript"></script>
<div class="inner-content">
    <div class="panel theme-panel">
        <div class="panel-heading">
            <span class="panel-title">
                Postulaciones <i class="fa fa-pencil-square-o"></i>
            </span>
        </div>
        <div class="panel-body table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <!--<th align="center"># Vacante</th>-->
                        <th>Empresa</th>
                        <th>Puesto</th>
                        <th>Sueldo</th>
                        <th>Vacante disponible</th>
                        <th>Vacante disponible</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $a = 0;
                    foreach ($this->paginator as $empresa) : // <-- change here!  
                        $a++;
                        ?>
                        <tr>
                            <!--<td><?php // echo $i++;    ?></td>-->
                            <td><?php echo $this->escapeHtml($empresa->nombre_comercial); ?></td>
                            <td><?php echo $this->escapeHtml($empresa->puesto); ?></td>
                            <td><?php echo $this->escapeHtml($empresa->sueldo); ?></td>
                            <td><?php echo $this->escapeHtml($empresa->vacantes_disponibles); ?></td>
                            <td><a href="#openModal" id="ver<?php echo $a; ?>" rfc="<?php echo $empresa->id_rfc; ?>"
                                   digito="<?php echo $empresa->digito_verificador; ?>" 
                                   vacante="<?php echo $empresa->num_vacante; ?>
                                   ">Ver</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <div id="openModal" class="modalDialog">
            <div>
                <div style="overflow: auto;" class="modalDialog1">
                    <a href="#close" title="Close" class="close">X</a>
                    <h1 align="center">Vacante</h1>
                    <div id="vacanteDiv">ss</div>
                </div>
            </div>
        </div>
        <?php
        // add at the end of the file after the table
        echo $this->paginationControl(
                // the paginator object
                $this->paginator,
                // the scrolling style
                'sliding',
                // the partial to use to render the control
                'partial/paginator.phtml',
                // the route to link to when a user clicks a control link
                array(
            'url' => $this->url('alumno', array('controller' => 'Alumno', 'action' => 'postulaciones'))
                )
        );
        ?>
    </div>
</div>
<script>
<?php for ($i = 1; $i <= $a; $i++) { ?>
        $("#ver<?php echo $i; ?>").on('click', function (event) {
            $('#vacanteDiv').html('<div align="center"><img src="http://img.ffffound.com/static-data/assets/6/77443320c6509d6b500e288695ee953502ecbd6d_m.gif"/></div>');
            $("#vacanteDiv").load("vacanteid", {id_rfc: $(this).attr("rfc"),
                digito_verificador: $(this).attr("digito"), num_vacante: $(this).attr("vacante")
            });
        });
<?php } ?>
</script>