<style>
    .modalDialog {
        position: fixed;
        font-family: Arial, Helvetica, sans-serif;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        background: rgba(0,0,0,0.8);
        z-index: 99999;
        opacity:0;
        -webkit-transition: opacity 400ms ease-in;
        -moz-transition: opacity 400ms ease-in;
        transition: opacity 400ms ease-in;
        pointer-events: none;
    }

    .modalDialog:target {
        opacity:1;
        pointer-events: auto;
    }
    @media (max-width: 767px) {
        .modalDialog > div {
            width: 300px;
        }
    }
    @media (max-height: 500px) {
        .modalDialog > div {
            height: 80%;
        }
        .modalDialog1 {
            height: 80%;
        }
    }
    @media (min-width: 768px) {
        .modalDialog > div {
            width: 700px;}

    }
    .modalDialog1{
        overflow: auto;
    }
    .modalDialog > div {
        /*width: 400px;*/
        /*overflow: auto;*/
        /*background-color:#3ea2e5;*/
        position: relative;
        margin: 7% auto;
        /*padding: 5px 20px 13px 20px;*/
        border-radius: 10px;
        /*background: #3ea2e5;*/
        /*background: -moz-linear-gradient(#3ea2e5, #999);*/
        background: -webkit-linear-gradient(#3ea2e5, #8BC5F8);
        background-color: #8BC5F8;
        /*background: -o-linear-gradient(#3ea2e5, #999);*/
    }

    .close {
        background: #606061;
        color: #FFFFFF;
        line-height: 25px;
        position: absolute;
        right: -12px;
        text-align: center;
        top: -10px;
        width: 24px;
        text-decoration: none;
        font-weight: bold;
        -webkit-border-radius: 12px;
        -moz-border-radius: 12px;
        border-radius: 12px;
        -moz-box-shadow: 1px 1px 3px #000;
        -webkit-box-shadow: 1px 1px 3px #000;
        box-shadow: 1px 1px 3px #000;
    }

    .close:hover { background: #00d9ff; }
</style>
<!--<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>--> 
<div class="inner-content" >
    <div class="panel theme-panel">
        <div class="alert alert-success" align="center" id="success" style="display: none;">
            <strong>Referencia Agregada</strong></div>
        <div class="alert alert-warning" align="center" id="eliminardiv" style="display: none;">Referencia eliminada</div>
        <div class="panel-heading">
            <span class="panel-title">
                Referencias Laborales <i class="fa fa-pencil-square-o"></i>
            </span>
        </div>
        <div class="panel-body table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Empresa</th>
                        <th>Inicio</th>
                        <th>Fin</th>
                        <th>Puesto</th>
                        <th>Suledo</th>
                        <th>Jefe Directo</th>
                        <th>Tel</th>
                        <th>Elminar</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $a = 0;
                    foreach ($this->paginator as $empresa) : // <-- change here!  
                        $a++;
                        ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($empresa->nombre_empresa); ?></td>
                            <td><?php echo $this->escapeHtml($empresa->fecha_inicio); ?></td>
                            <td><?php echo $this->escapeHtml($empresa->fecha_fin); ?></td>
                            <td><?php echo $this->escapeHtml($empresa->puesto); ?></td>
                            <td><?php echo $this->escapeHtml($empresa->sueldo); ?></td>
                            <td><?php echo $this->escapeHtml($empresa->jefe_directo); ?></td>
                            <td><?php echo $this->escapeHtml($empresa->tel_jefe_directo); ?></td>
                            <td><a href="#" id="eliminar<?php echo $a; ?>" empresa='<?php echo $empresa->nombre_empresa; ?>'>Eliminar</a></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            </br><a href="#openModal"><button  class="btn btn-default" href="#openModal">
                    Nuevo</button></a>

            <div id="openModal" class="modalDialog">
                <div>
                    <div style="overflow: auto;" class="modalDialog1">
                        <a href="#close" title="Close" class="close">X</a>
                        <h1 align="center">Referencias</h1>
                        <?php echo $form->getFormulario(); ?>
                    </div>
                </div>
            </div>
        </div>
        <?php
        // add at the end of the file after the table
        echo $this->paginationControl(
                // the paginator object
                $this->paginator,
                // the scrolling style
                'sliding',
                // the partial to use to render the control
                'partial/paginator.phtml',
                // the route to link to when a user clicks a control link
                array(
            'url' => $this->url('alumno', array('controller' => 'Alumno', 'action' => 'referenciaslaborales'))
                )
        );
        ?>
        <link src="<?php echo $this->basePath('css/popup.css'); ?>"media="screen" rel="stylesheet" type="text/css">
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#referencialab").submit(function (e) {
            $.ajax({
                type: "POST",
                url: "referenciaslaborales",
                data: $("#referencialab").serialize(), // serializes the form's elements.
                success: function ()
                {
                    setTimeout('location="#close"', 0);
                    var success = document.getElementById("success");
                    success.style.display = "block";
                    setTimeout(function () {
                        success.style.display = "none";
                        $("#main-content").load("referenciaslaborales");
                    }, 2000);
                }
            });

            e.preventDefault(); // avoid to execute the actual submit of the form.
        });
    });
<?php for ($i = 1; $i <= $a; $i++) { ?>
        $("#eliminar<?php echo $i; ?>").on('click', function (event) {
            //            $('#main-content').html('<div align="center"><img src="http://img.ffffound.com/static-data/assets/6/77443320c6509d6b500e288695ee953502ecbd6d_m.gif"/></div>');
            $.post('referenciaslaborales', {nombre_empresa: $(this).attr("empresa"), eliminar: 1})
                    .done(function () {
                        var success = document.getElementById("eliminardiv");
                        success.style.display = "block";
                        setTimeout(function () {
                            document.getElementById("eliminardiv").style.display = "none";
                            $("#main-content").load("referenciaslaborales");
                        }, 1500);
                    })
                    .fail(function (data) {
                        alert(data);
                    });

        });
<?php } ?>
</script>