<div class="inner-content">
    <div class="panel theme-panel" >
        <dl class="dl-horizontal">
            <dt>Nombre:</dt>
            <dd><?php echo $vacante["nombre_comercial"];?></dd>
            <dt>Giro:</dt>
            <dd><?php echo $vacante["giro_empresa"];?></dd>
            <dt>Telefono:</dt>
            <dd><?php echo $vacante["telefono"];?></dd>
            <dt>Extensión</dt>
            <dd><?php echo $vacante["extension"];?></dd>
            <dt>Email:</dt>
            <dd><?php echo $vacante["correo_electronico"];?></dd>
            <dt>Horario de Atencion</dt>
            <dd><?php echo $vacante["horario_atencion"];?></dd>
            <dt>Puesto:</dt>
            <dd><?php echo $vacante["puesto"];?></dd>
            <dt>Vacantes Disponibles:</dt>
            <dd><?php echo $vacante["vacantes_disponibles"];?></dd>
            <dt>Sueldo:</dt>
            <dd><?php echo $vacante["sueldo"];?></dd>
            <dt>Edad:</dt>
            <dd><?php echo $vacante["edad"];?></dd>
            <dt>Sexo:</dt>
            <dd><?php echo $vacante["sexo"];?></dd>
            <dt>Horario a Laborar:</dt>
            <dd><?php echo $vacante["horario_a_laborar"];?></dd>
            <dt>Dias a Laborar: </dt>
            <dd><?php echo $vacante["dias_a_laborar"];?></dd>
            <dt>Contacto:</dt>
            <dd><?php echo $vacante["contacto"];?></dd>
            <dt>Requisitos:</dt>
            <dd><?php echo $vacante["requisitos"];?></dd>
            <dt>Experiencia</dt>
            <dd><?php echo $vacante["experiencia"];?></dd>
            <dt>Actividades a realizar:</dt>
            <dd><?php echo $vacante["actividades_realizar"];?></dd>
        </dl>
    </div>
</div>
