<div class="col-xs-12 col-sm-6 col-lg-8" style="padding-left: 0px;">
    <div id="jssor_1" style="position: relative; border-radius: 15px;
         width: 600px; height: 500px; overflow: hidden; visibility: hidden; ">
        <!-- Loading Screen -->
        <div data-u="loading" style="position: absolute;">
            <div style="filter: alpha(opacity=70); opacity: 0.7;border-radius: 15px; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
            <div style="position:absolute;display:block;background:url('img/loading.gif') no-repeat center center;top:0px;left:0px;width:100%;height:100%;"></div>
        </div>
        <div data-u="slides" style="cursor: default; position: relative; border-radius: 15px;top: 0px; left: 0px; width: 600px; height: 500px; overflow: hidden;">
            <div data-p="112.50" style="display: none;">
                <img data-u="image" src="img/01.jpg" />
            </div>
            <div data-p="112.50" style="display: none;">
                <img data-u="image" src="img/02.jpg" />
            </div>
            <div data-p="112.50" style="display: none;">
                <img data-u="image" src="img/03.jpg" />
            </div>
            <div data-p="112.50" style="display: none;">
                <img data-u="image" src="img/04.jpg" />
            </div>
        </div>
        <!-- Bullet Navigator -->
        <div data-u="navigator" class="jssorb01" style="bottom:16px;right:16px;">
            <div data-u="prototype" style="width:12px;height:12px;"></div>
        </div>
        <!-- Arrow Navigator -->
        <span data-u="arrowleft" class="jssora05l" style="top:0px;left:8px;width:40px;height:40px;" data-autocenter="2"></span>
        <span data-u="arrowright" class="jssora05r" style="top:0px;right:8px;width:40px;height:40px;" data-autocenter="2"></span>
        <a href="http://www.jssor.com" style="display:none">Slideshow Maker</a>
    </div>
</div>
<div class="col-xs-12 col-sm-6 col-lg-8 col-lg-4 panel panel-default" style="padding-top: 10px;">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Inicio de Session</h3>
        </div>
        <div class="panel-body" align="center">
            <form method="post"  role="form" enctype="multipart/form-data" action="login">   
                <div class="input-group" style="padding-top: -2px;">
                    <span class="input-group-addon" id="basic-addon1">U</span>
                    <input type="text" class="form-control" placeholder="Username" name="id_rfc"
                           aria-describedby="basic-addon1">
                </div>
                <div class="input-group" style="padding-top: 3px;">
                    <span class="input-group-addon" id="basic-addon1">Pass</span>
                    <input type="password" class="form-control" placeholder="Username" name="password"
                           aria-describedby="basic-addon1">
                </div>
                <p style="padding-top: 3px;"><button type="submit" class="btn btn-primary">Enviar</button>
            </form>
        </div>
    </div>
    <div class="thumbnail">
        <img src="Estilos/images/BT.jpg" alt="..." style="width:60%;">
        <div class="caption">
            <p>
                <b>Bolsa de Trabajo</b><br />
                FES  Cuautitlán UNAM<br />
                Encargado del área: Flavio Lomeli <br />
                <br />
                Telefono: <a href="tel:5558069482">(55) 58069482 </a><br />
                Correo:<a href="mailto:bolsadetrabajofesc@gmail.com">
                    bolsadetrabajofesc@gmail.com
                </a></p>
            <p>
        </div>
    </div>
</div>