<div class="col-xs-12 poco" align="center">
     <h2>Misión</h2>
    <p align="justify" style="font-size: 18px;">
        <?php echo $datos?>
        Contribuir a la formación del capital humano que requiere el entorno laboral, mediante estrategias de inserción y desarrollo laboral orientadas a la comunidad universitaria de la FESC, para que con responsabilidad y compromiso social fortalezcan la calidad e innovación académica.
    </p>
</div>