<div class="col-xs-12 poco" align="center">
     <h2>Obejtivos</h2>
    <p align="justify" style="font-size: 15px;">
        Vincular a los estudiantes y egresados de la facultad de Estudios Superiores Cuautitlán con el sector productivo, privado e instituciones gubernamentales, fungiendo como enlace entre los departamentos de recursos humanos y la comunidad universitaria para la obtención de ofertas de empleo, prácticas profesionales y/o becarios. 
    </p>
</div>