<div class="col-xs-12 poco" align="center">
    <h2>Vision</h2>
    <p align="justify" style="font-size: 15px;">
        Ser un entorno de comunicación funcional y reconocida por su influencia dentro y fuera de la Universidad, un medio efectivo de colaboración entre la FESC y los sectores productivos y gubernamentales.
    </p>
    <p align="justify" style="font-size: 15px;">
        Ser la herramienta estratégica que vincule de manera efectiva, amplia y vigorosa a los estudiantes y egresados de la FESC con el campo profesional.
    </p>
    <p align="justify" style="font-size: 15px;">
        Constituir una guía permanente y una fuente autorizada de conocimientos e información vigente para los buscadores de empleo de la comunidad universitaria en todo lo referente a oportunidades de puestos de trabajo, autopromoción profesional, capacitación y actualización.
    </p>
</div>